name: build nikki

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    name: ${{ matrix.arch }}-${{ matrix.branch }} release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - openwrt-25.12

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: mihomo-alpha mihomo-meta nikki luci-app-nikki
          INDEX: 1
          NO_REFRESH_CHECK: true

      - name: compress
        run: |
          tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/nikki .

      # 从编译生成的 package 文件名中动态提取 luci-app-nikki 版本号
      - name: Set Release Tag
        id: release_tag
        run: |
          # 获取生成的 luci-app-nikki 包文件名并解析版本号
          FILE=$(ls bin/packages/${{ matrix.arch }}/nikki/luci-app-nikki* 2>/dev/null | head -n 1)
          
          if [ -n "$FILE" ]; then
            # 兼容 .ipk 和 .apk 两种文件命名格式
            VERSION=$(basename "$FILE" | sed -E 's/^luci-app-nikki[_-]//; s/\.(ipk|apk)$//; s/_[^_]+$//')
            echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=build-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi

      - name: Verify Tag Name
        run: echo "Generated tag name is ${{ steps.release_tag.outputs.tag_name }}"

      - name: upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz
          tag_name: ${{ steps.release_tag.outputs.tag_name }}
          generate_release_notes: true
